# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://127.0.0.1:5500/testselenium/2.html")
    self.driver.set_window_size(784, 835)
    self.driver.find_element(By.ID, "searchBook").click()
    self.driver.find_element(By.ID, "searchBook").send_keys("aaa")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "searchBook").click()
    self.driver.find_element(By.ID, "searchBook").send_keys("aaasđsdsd")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
