# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://127.0.0.1:5500/testselenium/3.html /testselenium/1.html")
    self.driver.set_window_size(784, 835)
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admi1")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert self.driver.switch_to.alert.text == "Invalid username or password!"
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()

  def test_login_attempts(self):
    self.driver.get("http://127.0.0.1:5500/testselenium/1.html")
    self.driver.set_window_size(784, 835)
    for _ in range(5):  # Thử 5 lần
        self.driver.find_element(By.ID, "username").send_keys("admin@example.com")
        self.driver.find_element(By.ID, "password").send_keys("wrongpassword")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        assert "Sai tên đăng nhập hoặc mật khẩu" in self.driver.switch_to.alert.text
        self.driver.switch_to.alert.accept()
  
  def test_invalid_account(self):
    self.driver.get("http://127.0.0.1:5500/testselenium/1.html")
    self.driver.set_window_size(784, 835)
    self.driver.find_element(By.ID, "username").send_keys("nonexistent@example.com")
    self.driver.find_element(By.ID, "password").send_keys("password123")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    assert "Sai tên đăng nhập hoặc mật khẩu" in self.driver.switch_to.alert.text


